# Generated by Django 5.0.4 on 2024-04-22 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mr_reporting_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreporting',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='dailyreporting',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='dailyreporting',
            name='doctor_time_in',
        ),
        migrations.RemoveField(
            model_name='dailyreporting',
            name='doctor_time_out',
        ),
        migrations.RemoveField(
            model_name='dailyreporting',
            name='gift',
        ),
        migrations.RemoveField(
            model_name='dailyreporting',
            name='gift_quantity',
        ),
        migrations.RemoveField(
            model_name='dailyreporting',
            name='gift_unit',
        ),
        migrations.RemoveField(
            model_name='dailyreporting',
            name='product',
        ),
        migrations.RemoveField(
            model_name='dailyreporting',
            name='product_quantity',
        ),
        migrations.RemoveField(
            model_name='dailyreporting',
            name='product_unit',
        ),
        migrations.RemoveField(
            model_name='dailyreporting',
            name='stockist',
        ),
        migrations.RemoveField(
            model_name='dailyreporting',
            name='stockist_time_in',
        ),
        migrations.RemoveField(
            model_name='dailyreporting',
            name='stockist_time_out',
        ),
        migrations.RemoveField(
            model_name='dailyreporting',
            name='submitted',
        ),
        migrations.CreateModel(
            name='DoctorAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_time_in', models.CharField(max_length=10)),
                ('doctor_time_out', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=False)),
                ('daily_reporting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reporting', to='mr_reporting_app.dailyreporting')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr_reporting_app.doctormaster')),
            ],
        ),
        migrations.CreateModel(
            name='GiftAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('daily_reporting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr_reporting_app.dailyreporting')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr_reporting_app.doctormaster')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr_reporting_app.giftmaster')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr_reporting_app.unitmaster')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('daily_reporting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr_reporting_app.dailyreporting')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr_reporting_app.doctormaster')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr_reporting_app.productmaster')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr_reporting_app.unitmaster')),
            ],
        ),
        migrations.CreateModel(
            name='StockistAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockist_time_in', models.CharField(max_length=10)),
                ('stockist_time_out', models.CharField(max_length=10)),
                ('daily_reporting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr_reporting_app.dailyreporting')),
                ('stockist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr_reporting_app.stockistmaster')),
            ],
        ),
    ]
