# Generated by Django 5.0.4 on 2024-04-12 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mr_reporting_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourprogram',
            name='from_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_area', to='mr_reporting_app.areamaster'),
        ),
        migrations.AlterField(
            model_name='tourprogram',
            name='to_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_area', to='mr_reporting_app.areamaster'),
        ),
    ]
