# Generated by Django 5.0.2 on 2024-04-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mr_reporting_app', '0002_remove_doctormaster_approval_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areamapping',
            name='area',
        ),
        migrations.AddField(
            model_name='areamapping',
            name='area',
            field=models.ManyToManyField(to='mr_reporting_app.areamaster'),
        ),
    ]
