# Generated by Django 5.0.4 on 2024-04-13 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mr_reporting_app', '0002_alter_tourprogram_from_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormaster',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr_reporting_app.areamaster'),
        ),
        migrations.AlterField(
            model_name='stockistmaster',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr_reporting_app.areamaster'),
        ),
    ]
