# Generated by Django 5.0.4 on 2024-04-26 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mr_reporting_app', '0002_stockistmaster_city_stockistmaster_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormaster',
            name='city',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mr_reporting_app.citymaster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctormaster',
            name='country',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mr_reporting_app.countrymaster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctormaster',
            name='state',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mr_reporting_app.statemaster'),
            preserve_default=False,
        ),
    ]
