# Generated by Django 5.0.4 on 2024-04-23 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mr_reporting_app', '0003_dailyreporting_designation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestsMaster',
        ),
    ]
