# Generated by Django 5.0.2 on 2024-04-08 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mr_reporting_app', '0003_remove_areamapping_area_areamapping_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areamapping',
            old_name='area',
            new_name='areas',
        ),
    ]
