# Generated by Django 5.0.4 on 2024-04-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mr_reporting_app', '0004_delete_requestsmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourprogram',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
